### PR TITLE
Lantern Grafana visualization is now being displayed.

### PR DESCRIPTION
**Pull request by bmath10**
https://oncprojectracking.healthit.gov/support/browse/LANTERN-19

### CODE REVIEW

**Review by edeyoung — COMMENTED** [review]
The url linked: http://ec2-3-228-127-99.compute-1.amazonaws.com/d-solo/9iJUikcZz/lantern?orgId=1&refresh=30s&from=1569854061884&to=1569854361884&panelId=2

Shows what I would expect:
image

Running the application shows something different:
image

**Comment by bmath10** [comment]
> The url linked: http://ec2-3-228-127-99.compute-1.amazonaws.com/d-solo/9iJUikcZz/lantern?orgId=1&refresh=30s&from=1569854061884&to=1569854361884&panelId=2
> 
> Shows what I would expect: ...
> 
> Running the application shows something different: ...

Trying hard reloading the page (either Cmd-Shift-R or, if you have the developer tools open, right click on the refresh button and choose 'Empty Cache and Hard Reload'). This just happened to me but hard reloading seemed to fix it. If that's not the case though, let me know!

**Comment by edeyoung** [comment]
that didn't work and this is the first time i've run the front end, so i don't expect it would have cached anything

**Review by edeyoung — APPROVED** [review]

**Review by mayerm94 — APPROVED** [review]
👍

**Pull request merged**
